19.11 19:22:12 TRACE: battle.sendtask : cacheRequest exception { scores => [1,0], _type => vdl/cache.battle.setScores, player1 => 19, player2 => 140, battleId => 15 }
19.11 19:22:12 TRACE: battle.sendtask : 
Called from snipe/slave/CacheConnection.hx line 199
Called from modules/VDLBattleModule.hx line 432
Called from modules/VDLBattleModule.hx line 388
Called from modules/VDLBattleModule.hx line 64
Called from modules/VDLBattleModule.hx line 42
Called from snipe/slave/Server.hx line 1176
19.11 19:34:02 TRACE: battle.sendtask : cacheRequest exception { scores => [1,0], _type => vdl/cache.battle.setScores, player1 => 140, player2 => 19, battleId => 16 }
19.11 19:34:02 TRACE: battle.sendtask : 
Called from snipe/slave/CacheConnection.hx line 199
Called from modules/VDLBattleModule.hx line 432
Called from modules/VDLBattleModule.hx line 388
Called from modules/VDLBattleModule.hx line 64
Called from modules/VDLBattleModule.hx line 42
Called from snipe/slave/Server.hx line 1176
19.11 19:53:02 TRACE: logoutPost battle exception: cacheRequest exception { roomId => 0, _type => vdl/cache.battle.infoRoom }
19.11 19:53:02 TRACE: 
Called from snipe/slave/CacheConnection.hx line 199
Called from modules/VDLBattleModule.hx line 498
Called from modules/VDLBattleModule.hx line 511
Called from snipe/slave/Server.hx line 994
19.11 19:54:37 TRACE: logoutPost battle exception: cacheRequest exception { roomId => 0, _type => vdl/cache.battle.infoRoom }
19.11 19:54:37 TRACE: 
Called from snipe/slave/CacheConnection.hx line 199
Called from modules/VDLBattleModule.hx line 498
Called from modules/VDLBattleModule.hx line 511
Called from snipe/slave/Server.hx line 994
19.11 19:57:05 TRACE: Invalid field access : id
19.11 19:57:05 TRACE: 
Called from modules/VDLBattleModule.hx line 144
Called from a C function
Called from snipe/slave/Server.hx line 685
Called from snipe/slave/CacheConnection.hx line 303
Called from snipe/slave/ThreadServerModified.hx line 202
